# References:
  * [https://studyopedia.com/pandas/dataframes-in-pandas/](https://studyopedia.com/pandas/dataframes-in-pandas/)

# 1- Import libraries

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# 1- Series


## 1.1- Question 1:
* Information:
  * N is number of integers will be generated by you

* Requirements:
  1. Generate N integers randomly (uniform distribution)
  2. Create a series (named s) from N number generated
  3. Show the results as in the output cell
    * Print series s
    * Print the index and values of s

* Guidelines:
  * To print the index: ```list(s.index)```
  * To print the values: ```list(s.values)```



In [ ]:
# Declare variables
N = 15

np.random.seed(0)

# YOUR CODE IS HERE


Series (s): 
0     44
1     47
2     64
3     67
4     67
5      9
6     83
7     21
8     36
9     87
10    70
11    88
12    88
13    12
14    58
dtype: int64
s.index:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
s.values:  [44, 47, 64, 67, 67, 9, 83, 21, 36, 87, 70, 88, 88, 12, 58]


## 1.2- Question 2:
* Information:
  * N is number of integers will be generated by you

* Requirements:
  1. Generate N integers randomly (uniform distribution), those will be the ```data``` of the series being created.
  2. Generate N integers randomly (uniform distribution), those will be the ```index``` of the series being created.
  3. Create a series (named s) from the data and the index generated
  3. Show the results as in the output cell
    * Print series s
    * Print the index and values of s

* Guidelines:
  * To print the index: ```list(s.index)```
  * To print the values: ```list(s.values)```



In [ ]:
# Declare variables
N = 15

np.random.seed(0)

# YOUR CODE IS HERE


Series (s): 
65    44
39    47
87    64
46    67
88    67
81     9
37    83
25    21
77    36
72    87
9     70
20    88
80    88
69    12
79    58
dtype: int64
s.index:   [65, 39, 87, 46, 88, 81, 37, 25, 77, 72, 9, 20, 80, 69, 79]
s.values:  [44, 47, 64, 67, 67, 9, 83, 21, 36, 87, 70, 88, 88, 12, 58]


## 1.3- Question 3:
* Information:
  * keys: the string contains the indices of the series being created

* Requirements:
  1. Generate N integers randomly (uniform distribution), those will be the ```data``` of the series being created; N is the length ```keys```

  2. Create a series (named s) from the data generated, and the keys is the list of characters stored in ```keys```

  3. Show the results as in the output cell
    * Print series s
    * Print the index and values of s

* Guidelines:
  * string to list: ```list(keys)```



In [ ]:
keys = 'ABCDEF'
np.random.seed(0)

# YOUR CODE IS HERE



Series (s): 
A    44
B    47
C    64
D    67
E    67
F     9
dtype: int64
s.index:   ['A', 'B', 'C', 'D', 'E', 'F']
s.values:  [44, 47, 64, 67, 67, 9]


## 1.4- Question 4:
* Information:
  * ```s```: a series of 20 items

* Requirements:
  1. Show attributes of series ```s```
  2. Call method: ```head```, ```tail``` and ```sample``` to show the first 3, the last 3 and sampled 3 items from series ```s```
  



In [ ]:
np.random.seed(0)
s = pd.Series(np.random.randint(0, 100, (20, )))

# YOUR CODE IS HERE


s.index:   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
s.values:  [44, 47, 64, 67, 67, 9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39, 87, 46, 88]
len(s):  20
s.size:  20
s.shape:  (20,)
s.dtype:  int64
s.ndim:  1
s.hasnans (hasnans means has Not-A-Number):  False
--------------------------------------------------
s.head(3): 
0    44
1    47
2    64
dtype: int64
s.tail(3): 
17    87
18    46
19    88
dtype: int64
s.sample(3): 
6     83
14    58
16    39
dtype: int64


## 1.5- Question 5:
* Requirements:
  1. Use method ```info()``` and ```describe()``` to show the information as in the output cell

In [ ]:
pd.options.display.float_format = '{:,.1f}'.format

# YOUR CODE IS HERE



Information of series (s.info): 
<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: None
Non-Null Count  Dtype
--------------  -----
20 non-null     int64
dtypes: int64(1)
memory usage: 288.0 bytes
None

Description of series (s.describe): 
count   20.0
mean    58.3
std     25.7
min      9.0
25%     42.8
50%     64.5
75%     84.0
max     88.0
dtype: float64


# 2- DataFrame

## 2.1- Question 1:
* Information:
  * X: numpy array 5-rows x 4-columns
  * c: list of 4 characters

* Requirements:
  1. Creat a DataFrame (named df) from data in X and columns in c
  2. Show the results as in the output cell

In [ ]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)

# YOUR CODE IS HERE


X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
DataFrame (df): 
    A   B   C   D
0  44  47  64  67
1  67   9  83  21
2  36  87  70  88
3  88  12  58  65
4  39  87  46  88


## 2.2- Question 2:


In [ ]:
rows = [
    {"Name": "An", "Programming": 8, "Comp-Arch": 10},
    {"Name": "Bình", "AI": 6, "Comp-Arch": 7},
    {"Name": "Tuấn", "Programming": 6.5, "DSA": 8},
    {"Name": "Nghĩa", "Discrete-Math": 9.5, "Programming": 8.5}
]
#YOUR CODE IS HERE
df = pd.DataFrame(rows)


DataFrame (df): 
    Name  Programming  Comp-Arch  AI  DSA  Discrete-Math
0     An          8.0       10.0 NaN  NaN            NaN
1   Bình          NaN        7.0 6.0  NaN            NaN
2   Tuấn          6.5        NaN NaN  8.0            NaN
3  Nghĩa          8.5        NaN NaN  NaN            9.5

What is NaN? (Try to understand)


## 2.3- Question 3:

* Requirements:
  1. Create a DataFrame (named df) from columns given in ```student```, ```rank```, and ```mark```
  2. Show the result as in the output cell

In [ ]:
# Variables
student =  ["Amit", "John", "Jacob", "David", "Steve"]
rank = [1, 4, 3, 5, 2]
mark = [95, 70, 80, 60, 90]

#YOUR CODE IS HERE


DataFrame (df): 
  stdudent  rank  mark
0     Amit     1    95
1     John     4    70
2    Jacob     3    80
3    David     5    60
4    Steve     2    90


## 2.4- Question 4:

* Requirements:
  1. Create a DataFrame (named df) from columns given in ```rank``` and ```mark```, and use ```student``` as its its index
  2. Use ```list(df.index)``` to get list of index
  2. Show the results as in the output cell

In [ ]:
# Variables
student =  ["Amit", "John", "Jacob", "David", "Steve"]
rank = [1, 4, 3, 5, 2]
mark = [95, 70, 80, 60, 90]

#YOUR CODE IS HERE


DataFrame (df): 
       rank  mark
Amit      1    95
John      4    70
Jacob     3    80
David     5    60
Steve     2    90
index of df:  ['Amit', 'John', 'Jacob', 'David', 'Steve']


## 2.5- Question 5:
* Information:
  * ```df```: a DataFrame

* Requirements:
  1. Show the information of ```df``` as in the output cell
  

In [ ]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)
df = pd.DataFrame(np.random.randint(0, 100, (5,4)),
                  columns=list("ABCD"),
                  index=['row-1', 'row-2', 'row-3', 'row-4', 'row-5'])

#YOUR CODE IS HERE



X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
DataFrame (df): 
        A   B   C   D
row-1  81  37  25  77
row-2  72   9  20  80
row-3  69  79  47  64
row-4  82  99  88  49
row-5  29  19  19  14

list(df.index):  ['row-1', 'row-2', 'row-3', 'row-4', 'row-5']

list(df.values): [array([81, 37, 25, 77]), array([72,  9, 20, 80]), array([69, 79, 47, 64]), array([82, 99, 88, 49]), array([29, 19, 19, 14])]
len(df):  5
df.shape:  (5, 4)
df.size:  20
type of columns (df.dtypes): 
A    int64
B    int64
C    int64
D    int64
dtype: object
df.ndim:  2

--------------------------------------------------
df.head(3): 
        A   B   C   D
row-1  81  37  25  77
row-2  72   9  20  80
row-3  69  79  47  64
df.tail(3): 
        A   B   C   D
row-3  69  79  47  64
row-4  82  99  88  49
row-5  29  19  19  14
df.sample(3): 
        A   B   C   D
row

## 2.6- Question 6:
* Requirements:
  1. Transpose DataFrame df and show the result as in the output cell
  * Guidelines:
    * use ```df.T```


In [ ]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)
df = pd.DataFrame(np.random.randint(0, 100, (5,4)),
                  columns=list("ABCD"),
                  index=['row-1', 'row-2', 'row-3', 'row-4', 'row-5'])

#YOUR CODE IS HERE


X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
DataFrame df: 
        A   B   C   D
row-1  81  37  25  77
row-2  72   9  20  80
row-3  69  79  47  64
row-4  82  99  88  49
row-5  29  19  19  14

DataFrame df.T: 
   row-1  row-2  row-3  row-4  row-5
A     81     72     69     82     29
B     37      9     79     99     19
C     25     20     47     88     19
D     77     80     64     49     14


## 2.7- Question 7
* Requirements:
  1. Use method ```info()``` and ```describe()``` (transpose the result of ```describe()``` )to show the information as in the output cell

In [ ]:
np.random.seed(0)

X = np.random.randint(0, 100, (5,4))
c = list("ABCD")
print("X: "); print(X)
print("c:", c)
print()
print("-"*100)
df = pd.DataFrame(np.random.randint(0, 100, (5,4)),
                  columns=list("ABCD"),
                  index=['row-1', 'row-2', 'row-3', 'row-4', 'row-5'])
pd.options.display.float_format = '{:,.1f}'.format

# YOUR CODE IS HERE


X: 
[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]
 [88 12 58 65]
 [39 87 46 88]]
c: ['A', 'B', 'C', 'D']

----------------------------------------------------------------------------------------------------
Information of DataFrame (df.info()): 
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row-1 to row-5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes
None

Description of series (df.describe()): 
   count  mean  std  min  25%  50%  75%  max
A    5.0  66.6 21.8 29.0 69.0 72.0 81.0 82.0
B    5.0  48.6 38.9  9.0 19.0 37.0 79.0 99.0
C    5.0  39.8 29.2 19.0 20.0 25.0 47.0 88.0
D    5.0  56.8 26.9 14.0 49.0 64.0 77.0 80.0


# 3- Explore the information of datasets for machine learning

## 3.1- Dataset: ***sklearn.datasets.load_iris***
* References:
  * Link: [https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html)

* Information:
  * ```X```: a Dataframe, contains all samples of the dataset.
    * rows: sample/observations/data points
    * cols: features/variables/attributes
  * ```y```: a series, **contains the label for the corresponding sample, i.e., the sample has the same index in ```y```**, for examples,
    * Sample X.iloc[0] has label is y[0]
    * Sample X.iloc[1] has label is y[1]
    * and so on

* Requirements:
  * Show the information of the dataset as in the output cell.
  

In [ ]:
from sklearn.datasets import load_iris

blob = load_iris(as_frame= True)
X, y = blob.data, blob.target
print("type(X): ", type(X))
print("type(y): ", type(y))

print()
print('='*100)

#YOUR CODE IS HERE


type(X):  <class 'pandas.core.frame.DataFrame'>
type(y):  <class 'pandas.core.series.Series'>

Dataset: IRIS
----------------------------------------------------------------------------------------------------
Number of samples, len(x):  150
Number of features, X.shape[1]:  4
Name of features, list(X.columns):
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Columns's data type, X.dtypes
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object
Data type of label, y.dtype:  int64

--------------------------------------------------
Information of X, X.info(): 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 no

## 3.2- Explore other datasets in sklearn
* References:
  * Link: [https://scikit-learn.org/stable/datasets/toy_dataset.html](https://scikit-learn.org/stable/datasets/toy_dataset.html)

  * Requirements:
    1. Do similar tasks in Question 3.1 given above to explore the other toy datasets in sklearns. Check the link given above for the name of each dataset.
    * Guidelines:
      * Create one section for each dataset
      

In [ ]:
# YOUR CODE IS HERE

# 4- Create Dataframe showing data files and their labels

## 4.1- Question 1: **BBC-NEWS**

In [ ]:
# RUN THIS CELL TO DOWNLOAD THE DATASET
!rm -f bbc-fulltext.zip
!rm -rf bbc
!wget http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip
!unzip -q bbc-fulltext.zip


--2023-05-10 04:12:53--  http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip
Resolving mlg.ucd.ie (mlg.ucd.ie)... 137.43.93.132
Connecting to mlg.ucd.ie (mlg.ucd.ie)|137.43.93.132|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2874079 (2.7M) [application/zip]
Saving to: ‘bbc-fulltext.zip’

bbc-fulltext.zip    100%[===================>]   2.74M  4.48MB/s    in 0.6s    

2023-05-10 04:12:55 (4.48 MB/s) - ‘bbc-fulltext.zip’ saved [2874079/2874079]



### Question-1's requirements
* Information:
  * **files**: Python's list, contains all file files in the dataset
  * **labels**: Python's list, contains the label for the corresponding file in **files**, **corresponding** means **at the same index**

* Requurements:
  1. Create a DataFrame with columns are the data in ```files``` and ```labels```
  2. Show the results as in the output cell

* Guideline:
  * Use ```df.sample(10)``` to show 10 sampled randomly from the created dataframe

In [ ]:
from pathlib import Path

path_to_data = './bbc'
# List all files
all_paths = Path(path_to_data).rglob('*.txt')
files = [str(path) for path in all_paths]
labels = [file.split('/')[-2] for file in files]
print("files: ", files)
print("labels:", labels)
print("="*100)

#YOUR CODE IS HERE


files:  ['bbc/business/045.txt', 'bbc/business/007.txt', 'bbc/business/121.txt', 'bbc/business/410.txt', 'bbc/business/235.txt', 'bbc/business/404.txt', 'bbc/business/302.txt', 'bbc/business/018.txt', 'bbc/business/041.txt', 'bbc/business/293.txt', 'bbc/business/247.txt', 'bbc/business/129.txt', 'bbc/business/369.txt', 'bbc/business/416.txt', 'bbc/business/423.txt', 'bbc/business/379.txt', 'bbc/business/505.txt', 'bbc/business/431.txt', 'bbc/business/298.txt', 'bbc/business/179.txt', 'bbc/business/010.txt', 'bbc/business/449.txt', 'bbc/business/197.txt', 'bbc/business/497.txt', 'bbc/business/406.txt', 'bbc/business/442.txt', 'bbc/business/425.txt', 'bbc/business/011.txt', 'bbc/business/359.txt', 'bbc/business/181.txt', 'bbc/business/271.txt', 'bbc/business/136.txt', 'bbc/business/417.txt', 'bbc/business/343.txt', 'bbc/business/037.txt', 'bbc/business/300.txt', 'bbc/business/283.txt', 'bbc/business/201.txt', 'bbc/business/057.txt', 'bbc/business/164.txt', 'bbc/business/432.txt', 'bbc/bu

## 4.2- Question 2: **Animals10samll**
* Requirements:
  * Do similar tasks in Question-4.1 for dataset **Animals10samll**

In [ ]:
%%shell
pip -q install --upgrade --no-cache-dir gdown
gdown -q 1Do8SXKm4rmXW-phHlejV-udLfhSyYgKk
echo 'download: done => file: animals10small.zip'
rm -rf ./animals10small/
unzip -q animals10small.zip
echo 'Data files in: /content/animals10small/'

download: done => file: animals10small.zip
Data files in: /content/animals10small/


In [ ]:
# YOUR CODE IS HERE

## 4.2- Question 3: **Flower**
* Requirements:
  * Do similar tasks in Question-4.1 for dataset **Flower**

In [ ]:
!rm -f flower_photos.tgz
!wget https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz
!tar -xzf flower_photos.tgz
path_to_data = './flower_photos'

--2023-05-10 04:13:07--  https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.253.122.128, 172.253.63.128, 142.251.163.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.253.122.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 228813984 (218M) [application/x-compressed-tar]
Saving to: ‘flower_photos.tgz’

flower_photos.tgz   100%[===================>] 218.21M   176MB/s    in 1.2s    

2023-05-10 04:13:09 (176 MB/s) - ‘flower_photos.tgz’ saved [228813984/228813984]



In [ ]:
# YOUR CODE IS HERE

## 4.2- Question 3: **OxfordPet**
* Requirements:
  * Do similar tasks in Question-4.1 for dataset **OxfordPet**
  * **OxfordPet**: has been examplified in previous questions, about "Indexing" with Numpy

In [1]:
# Download the dataset
!rm -f images.tar.gz annotations.tar.gz
!wget https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz
!wget https://thor.robots.ox.ac.uk/~vgg/data/pets/annotations.tar.gz
!tar -xzf images.tar.gz
!tar -xzf annotations.tar.gz

--2024-04-10 11:31:24--  https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz
Resolving thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 129.67.95.98
Connecting to thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)|129.67.95.98|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://thor.robots.ox.ac.uk/datasets/pets/images.tar.gz [following]
--2024-04-10 11:31:25--  https://thor.robots.ox.ac.uk/datasets/pets/images.tar.gz
Reusing existing connection to thor.robots.ox.ac.uk:443.
HTTP request sent, awaiting response... 200 OK
Length: 791918971 (755M) [application/octet-stream]
Saving to: ‘images.tar.gz’

images.tar.gz       100%[===================>] 755.23M  23.9MB/s    in 33s     

2024-04-10 11:31:58 (23.0 MB/s) - ‘images.tar.gz’ saved [791918971/791918971]

--2024-04-10 11:31:58--  https://thor.robots.ox.ac.uk/~vgg/data/pets/annotations.tar.gz
Resolving thor.robots.ox.ac.uk (thor.robots.ox.ac.uk)... 129.67.95.98
Connecting to thor.robots.ox.ac.

In [ ]:
# YOUR CODE IS HERE